### ISSUE TITLE
Erro no Build

### ISSUE THREAD

**Issue by ThalesMatoso** [gerencianet/gn-api-sdk-node#10]
Possuo o seguinte erro ao gerar o Build, todo o processo de desenvolvimento deu certo.
mas ao gerar o build ele alega esse erro dentro da lib.

![image](https://user-images.githubusercontent.com/20910274/66423641-75381080-e9e2-11e9-97ab-6e4c681cace4.png)

**Comment by jvoliveiraGN** [comment]
Oi @ThalesMatoso tudo bem?
Nos desculpe ter deixado passar essa issue!
Temos uma nova versão da SDK caso seja de seu interesse!
Incluindo os endpoints do pix!
Quaisquer dúvidas estamos à disposição!
