### ISSUE TITLE
Suporte a API Pix

### ISSUE THREAD

**Issue by subversivo58** [gerencianet/gn-api-sdk-node#13]
Existe um plano para suportar a API Pix neste sdk?

**Comment by jvoliveiraGN** [comment]
Oi @subversivo58 tudo bem? 😄 
Existe sim! A SDK está na fase final de testes e liberaremos a atualização em breve!
Acredito que nessa semana mesmo já esteja disponível.

**Comment by jvoliveiraGN** [comment]
Oi @subversivo58 tudo bem?
Acabamos de liberar a atualização incluindo os endpoints do pix!
Release v2.0.0! :D
