### ISSUE TITLE
Quebrou o retorno

### ISSUE THREAD

**Issue by joaummachado** [gerencianet/gn-api-sdk-node#16]
Estou utilizando o SDK de vocês, porém quando colocaram console.log, talvez em uma tentativa de debugar, quebraram o código totalmente.  Assim, não consigo pegar o retorno da API

https://github.com/gerencianet/gn-api-sdk-node/blob/5f555a482b28bedbe1ad94f27d00c601026e87ff/lib/gn-endpoints.js#L68

**Comment by joaummachado** [comment]
Pra resolver eu dei um fork aqui. A solução:

`GnEndpoints.prototype.req = function (callback) {
  let req = this.getParams.call(this, this.endpoint.route)
  req['method'] = this.endpoint.method

  axios(req)
    .then((res) => {
      callback(false, res, res.data)
    })
    .catch((error) => {
      callback(true, error.response, error.response.data)
    })
}`

**Comment by felipdc** [comment]
@joaummachado Conseguiu resolver o problema? Abri uma issue #20 a respeito desse problema...
