### ISSUE TITLE
Dúvida: Atualizar valores, dados de cartão e desconto no primeiro pagamento (trial)

### ISSUE THREAD

**Issue by mayconjcm** [gerencianet/gn-api-sdk-node#2]
Fala pessoal,
Primeiramente gostaria de elogiar a API, ficou muito bem escrita e documentada!

Estou implementando a Gerencia Net Node API em um cliente, pra lidar com Assinatura utilizando o Checkout Transparente (cartão e boleto). É exatamente o que precisamos aqui no escritório. Estamos querendo abandonar o PayPal Subscriptions de vez!

O que eu gostaria de saber é:

1. Se o cliente pode Atualizar os dados do cartão de crédito (Payment Token) quando quiser, sem a necessidade de cancelar a Assinatura e ter que inciar outra. Assim como acontece no Netflix/Deezer/Spotify?

2. A outra dúvida é se é possível também atualizar o Plano do Cliente, assim como o seu Preço (R$), quando o cliente quiser fazer um Upgrade de Plano?

3. Pra finalizar, gostaria de saber se tem como gerar uma transação com desconto no primeiro pagamento, permitindo, por exemplo, oferecer o primeiro mês Gratuito, estilo Netflix também! :smile: 

Obrigado pela paciência.

Att. Maycon Mesquita

**Comment by franciscotfmc** [comment]
Olá @mayconjcm 

Agradecemos o feedback!

Infelizmente ainda não temos implementado nenhuma das três funcionalidades que você mencionou.
Já discutimos estes problemas e estamos cientes que é importante permitirmos estas alterações.

Com o seu contato, colocamos +1 nestes pontos da nossa TO DO list, :)

Pretendemos disponibilizar estas modificações em breve!
