### ISSUE TITLE
GnEndpoints.prototype.req não está chamando a função callback

### ISSUE THREAD

**Issue by felipdc** [gerencianet/gn-api-sdk-node#20]
Na função **GnEndpoints.prototype.req**, o atributo **callback** está definido, porém não é invocado.

Também, imagino que seja interessante definir a função como _async_, já que facilita a invocação e tratamento de erros.

**Comment by jvoliveiraGN** [comment]
Oi @felipdc tudo bem? Vamos avaliar a PR #21 e realizar alguns testes!
Assim que possível te dou um retorno, ok? 😄 
Vale lembrar que temos uma comunidade no Discord com mais de 1000 desenvolvedores, onde é possível tirar dúvidas e ter contato com a equipe de suporte técnico de maneira mais rápida! Caso queira fazer parte, é só clicar [aqui](https://discord.gg/bHKhsj9WCj)
Quaisquer dúvidas, estamos à disposição!

**Comment by jvoliveiraGN** [comment]
Oi @felipdc tudo bem? 😄 
Muito obrigado pela contribuição! As vezes a gente deixa algum detalhe passar! rs
Correção adicionada na Release 2.0.4! #21
