### ISSUE TITLE
Sem timeout ao chamar função pixListReceived

### ISSUE THREAD

**Issue by igorpdasilvaa** [gerencianet/gn-api-sdk-node#26]
Estou utilizando a versão 2.0.8 do gn-api-sdk-node, e tenho um problema que ao chamar a função pixListReceived passando filtro de data de inicio e data de fim quando oscila a internet a promise nunca é resolvida, nem da timeout e nem nada. com isso a aplicação acaba ficando presa pra sempre esperando a conclusão dessa função

**Comment by jvoliveiraGN** [comment]
Olá @igorpdasilvaa tudo certo?
Os demais endpoints funcionavam corretamente?
Não tivemos nenhum relato semelhante, fiz alguns testes e também não consegui reproduzir a falha.
Recomendo testar a versão mais recente disponibilizada, e caso tenha alguma dúvida sobre implementação, recomendamos nossa comunidade do Discord, lá conseguimos auxiliar de uma maneira mais rápida e dinâmica.

Convite para o Discord: https://discord.gg/ptGHMtczcV
