### ISSUE TITLE
Dúvida: npm instala outros 74 pacotes

### ISSUE THREAD

**Issue by humbertocruz** [gerencianet/gn-api-sdk-node#3]
Dúvuda: estou tentando implementar a integração em NodeJS e ao instalar via npm foram instalados outros 74 pacotes dentro do diretorio node_modules e isso causa um certo problema na minha aplicação.. está certo isso ?

**Comment by franciscotfmc** [comment]
Olá @humbertocruz 

Você provavelmente está usando a versão 3 do npm. Na versão
3 as dependências não ficam mais aninhadas (salvo em alguns casos). O objetivo disso é não duplicar dependências dentro de dependências.

Esse comportamento do npm não é um problema. Caso tenha encontrado algum problema com a SDK, por favor poste o erro para que possamos te ajudar.
