### ISSUE TITLE
posso criar uma subconta (marketplace) através da api?

### ISSUE THREAD

**Issue by petkovic43** [gerencianet/gn-api-sdk-node#4]

**Comment by franciscotfmc** [comment]
@petkovic43 criação de subusers somente através da interface pelo sistema web. O marketplace que você escreveu na sua pergunta é uma forma de repassar o valor de um pagamento para uma ou mais contas, e isso sim é possível via api.

Dê uma olhada na [documentação](https://dev.gerencianet.com.br/docs/marketplace-introducao).
Caso tenha mais alguma dúvida em relação à API peço que entre em contato através do e-mail  suportetecnico@gerencianet.com.br ou crie um ticket acessando o "fale conosco" da Gerencianet.
