### ISSUE TITLE
Como conseguir o Payment_token por nodejs?

### ISSUE THREAD

**Issue by IgorDePaula** [gerencianet/gn-api-sdk-node#8]
Como conseguir o Payment_token por nodejs?

**Comment by WhinterGoncalves** [comment]
Olá Igor, 

O _Payment Token_ é obtido por meio do código Javascript disponibilizado pela Gerencianet em nossa  [Documentação Oficial](https://dev.gerencianet.com.br/docs/pagamento-com-cartao#section-1-1-obten-o-do-payment_token) e é executado no _frontend_ no sistema do cliente. Desta forma, é necessário chamar a função através de uma _engine_ de _views_ do _Node.JS_ como o _ejs_ (app.set('view engine', 'ejs')), por exemplo.

**Comment by IgorDePaula** [comment]
Mais de 6 meses pra dar esta resposta? Já estou decepcionado com a maxipago, agora com vocês.

Não existe uma unica solução aprazível e fácil para os desenvolvedores, principalmente quando se fala de web e mobile.

**Comment by wilkhp29** [comment]
documentaçäo muito defasada
